// <auto-generated />
using System;
using Baselib.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Baselib.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260504083125_AlignCrudActionTypesWithIme")]
    partial class AlignCrudActionTypesWithIme
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Baselib.Entities.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("ParentDepartmentId")
                        .HasColumnType("int");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("ParentDepartmentId");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "YT",
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Name = "Yönetim"
                        },
                        new
                        {
                            Id = 2,
                            Code = "BT",
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Name = "Bilgi Teknolojileri",
                            ParentDepartmentId = 1
                        },
                        new
                        {
                            Id = 3,
                            Code = "IK",
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Name = "İnsan Kaynakları",
                            ParentDepartmentId = 1
                        });
                });

            modelBuilder.Entity("Baselib.Entities.Menu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Icon")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.Property<int?>("PermissionId")
                        .HasColumnType("int");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Url")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.HasIndex("PermissionId");

                    b.ToTable("Menus");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Icon = "bi-speedometer2",
                            IsActive = true,
                            Name = "Dashboard",
                            Order = 1,
                            Url = "/Admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Icon = "bi-people",
                            IsActive = true,
                            Name = "Kullanıcılar",
                            Order = 2,
                            PermissionId = 1,
                            Url = "/Admin/Users"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Icon = "bi-shield-check",
                            IsActive = true,
                            Name = "Roller",
                            Order = 3,
                            PermissionId = 5,
                            Url = "/Admin/Roles"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Icon = "bi-key",
                            IsActive = true,
                            Name = "İzinler",
                            Order = 4,
                            PermissionId = 9,
                            Url = "/Admin/Permissions"
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Icon = "bi-diagram-3",
                            IsActive = true,
                            Name = "Departmanlar",
                            Order = 5,
                            PermissionId = 13,
                            Url = "/Admin/Departments"
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Icon = "bi-menu-button",
                            IsActive = true,
                            Name = "Menüler",
                            Order = 6,
                            PermissionId = 17,
                            Url = "/Admin/Menus"
                        });
                });

            modelBuilder.Entity("Baselib.Entities.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActionName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("CRUDActionType")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ControllerName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ActionName = "List",
                            CRUDActionType = 1,
                            Code = "Users_Read",
                            ControllerName = "Users",
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Kullanıcı listeleme ve görüntüleme",
                            IsActive = true,
                            Name = "Kullanıcı Listele"
                        },
                        new
                        {
                            Id = 2,
                            ActionName = "Add",
                            CRUDActionType = 2,
                            Code = "Users_Create",
                            ControllerName = "Users",
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Kullanıcı oluşturma",
                            IsActive = true,
                            Name = "Kullanıcı Oluştur"
                        },
                        new
                        {
                            Id = 3,
                            ActionName = "Update",
                            CRUDActionType = 3,
                            Code = "Users_Update",
                            ControllerName = "Users",
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Kullanıcı güncelleme",
                            IsActive = true,
                            Name = "Kullanıcı Güncelle"
                        },
                        new
                        {
                            Id = 4,
                            ActionName = "Delete",
                            CRUDActionType = 6,
                            Code = "Users_Delete",
                            ControllerName = "Users",
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Kullanıcı silme",
                            IsActive = true,
                            Name = "Kullanıcı Sil"
                        },
                        new
                        {
                            Id = 5,
                            ActionName = "List",
                            CRUDActionType = 1,
                            Code = "Roles_Read",
                            ControllerName = "Roles",
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Rol listeleme ve görüntüleme",
                            IsActive = true,
                            Name = "Rol Listele"
                        },
                        new
                        {
                            Id = 6,
                            ActionName = "Add",
                            CRUDActionType = 2,
                            Code = "Roles_Create",
                            ControllerName = "Roles",
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Rol oluşturma",
                            IsActive = true,
                            Name = "Rol Oluştur"
                        },
                        new
                        {
                            Id = 7,
                            ActionName = "Update",
                            CRUDActionType = 3,
                            Code = "Roles_Update",
                            ControllerName = "Roles",
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Rol güncelleme",
                            IsActive = true,
                            Name = "Rol Güncelle"
                        },
                        new
                        {
                            Id = 8,
                            ActionName = "Delete",
                            CRUDActionType = 6,
                            Code = "Roles_Delete",
                            ControllerName = "Roles",
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Rol silme",
                            IsActive = true,
                            Name = "Rol Sil"
                        },
                        new
                        {
                            Id = 9,
                            ActionName = "List",
                            CRUDActionType = 1,
                            Code = "Permissions_Read",
                            ControllerName = "Permissions",
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "İzin listeleme ve görüntüleme",
                            IsActive = true,
                            Name = "İzin Listele"
                        },
                        new
                        {
                            Id = 10,
                            ActionName = "Add",
                            CRUDActionType = 2,
                            Code = "Permissions_Create",
                            ControllerName = "Permissions",
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "İzin oluşturma",
                            IsActive = true,
                            Name = "İzin Oluştur"
                        },
                        new
                        {
                            Id = 11,
                            ActionName = "Update",
                            CRUDActionType = 3,
                            Code = "Permissions_Update",
                            ControllerName = "Permissions",
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "İzin güncelleme",
                            IsActive = true,
                            Name = "İzin Güncelle"
                        },
                        new
                        {
                            Id = 12,
                            ActionName = "Delete",
                            CRUDActionType = 6,
                            Code = "Permissions_Delete",
                            ControllerName = "Permissions",
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "İzin silme",
                            IsActive = true,
                            Name = "İzin Sil"
                        },
                        new
                        {
                            Id = 13,
                            ActionName = "List",
                            CRUDActionType = 1,
                            Code = "Departments_Read",
                            ControllerName = "Departments",
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Departman listeleme ve görüntüleme",
                            IsActive = true,
                            Name = "Departman Listele"
                        },
                        new
                        {
                            Id = 14,
                            ActionName = "Add",
                            CRUDActionType = 2,
                            Code = "Departments_Create",
                            ControllerName = "Departments",
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Departman oluşturma",
                            IsActive = true,
                            Name = "Departman Oluştur"
                        },
                        new
                        {
                            Id = 15,
                            ActionName = "Update",
                            CRUDActionType = 3,
                            Code = "Departments_Update",
                            ControllerName = "Departments",
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Departman güncelleme",
                            IsActive = true,
                            Name = "Departman Güncelle"
                        },
                        new
                        {
                            Id = 16,
                            ActionName = "Delete",
                            CRUDActionType = 6,
                            Code = "Departments_Delete",
                            ControllerName = "Departments",
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Departman silme",
                            IsActive = true,
                            Name = "Departman Sil"
                        },
                        new
                        {
                            Id = 17,
                            ActionName = "List",
                            CRUDActionType = 1,
                            Code = "Menus_Read",
                            ControllerName = "Menus",
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Menü listeleme ve görüntüleme",
                            IsActive = true,
                            Name = "Menü Listele"
                        },
                        new
                        {
                            Id = 18,
                            ActionName = "Add",
                            CRUDActionType = 2,
                            Code = "Menus_Create",
                            ControllerName = "Menus",
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Menü oluşturma",
                            IsActive = true,
                            Name = "Menü Oluştur"
                        },
                        new
                        {
                            Id = 19,
                            ActionName = "Update",
                            CRUDActionType = 3,
                            Code = "Menus_Update",
                            ControllerName = "Menus",
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Menü güncelleme",
                            IsActive = true,
                            Name = "Menü Güncelle"
                        },
                        new
                        {
                            Id = 20,
                            ActionName = "Delete",
                            CRUDActionType = 6,
                            Code = "Menus_Delete",
                            ControllerName = "Menus",
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Menü silme",
                            IsActive = true,
                            Name = "Menü Sil"
                        });
                });

            modelBuilder.Entity("Baselib.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("IpAddress")
                        .HasColumnType("longtext");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UserAgent")
                        .HasColumnType("longtext");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Baselib.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Yönetici",
                            IsActive = true,
                            Name = "Admin"
                        });
                });

            modelBuilder.Entity("Baselib.Entities.RolePermission", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("RolePermissions");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            PermissionId = 1
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 2
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 3
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 4
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 5
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 6
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 7
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 8
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 9
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 10
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 11
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 12
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 13
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 14
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 15
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 16
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 17
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 18
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 19
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 20
                        });
                });

            modelBuilder.Entity("Baselib.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("FirstName")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LastName")
                        .HasColumnType("longtext");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Phone")
                        .HasColumnType("longtext");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 1,
                            Email = "admin@baselib.com",
                            FirstName = "Admin",
                            IsActive = true,
                            LastName = "User",
                            PasswordHash = "$2b$10$br5S4nxaGpEKXOPtd/mdvuKBmNoiWHPoJ8MRF43wYnOB/JbBz2o7u",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("Baselib.Entities.UserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            RoleId = 1
                        });
                });

            modelBuilder.Entity("Baselib.Entities.Department", b =>
                {
                    b.HasOne("Baselib.Entities.Department", "ParentDepartment")
                        .WithMany("SubDepartments")
                        .HasForeignKey("ParentDepartmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ParentDepartment");
                });

            modelBuilder.Entity("Baselib.Entities.Menu", b =>
                {
                    b.HasOne("Baselib.Entities.Menu", "Parent")
                        .WithMany("SubMenus")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Baselib.Entities.Permission", "Permission")
                        .WithMany("Menus")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Parent");

                    b.Navigation("Permission");
                });

            modelBuilder.Entity("Baselib.Entities.RefreshToken", b =>
                {
                    b.HasOne("Baselib.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Baselib.Entities.RolePermission", b =>
                {
                    b.HasOne("Baselib.Entities.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Baselib.Entities.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Baselib.Entities.User", b =>
                {
                    b.HasOne("Baselib.Entities.Department", "Department")
                        .WithMany("Users")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Baselib.Entities.UserRole", b =>
                {
                    b.HasOne("Baselib.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Baselib.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Baselib.Entities.Department", b =>
                {
                    b.Navigation("SubDepartments");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Baselib.Entities.Menu", b =>
                {
                    b.Navigation("SubMenus");
                });

            modelBuilder.Entity("Baselib.Entities.Permission", b =>
                {
                    b.Navigation("Menus");

                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("Baselib.Entities.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Baselib.Entities.User", b =>
                {
                    b.Navigation("RefreshTokens");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
