import { useMemo, useState } from 'react'
import { api } from '../../api/client'
import type { Permission, Role, RoleInput } from '../../api/contracts'
import { useApiData } from '../../api/useApiData'
import { Panel, SectionHead, Button, Badge, IconButton, Modal, Field, TextInput, Textarea, Check } from '../ui'
import { IconPlus, IconEdit, IconTrash } from '../icons'

export default function Roles() {
  const roles = useApiData(api.roles); const permissions = useApiData(api.permissions); const [editing, setEditing] = useState<Role | 'new' | null>(null)
  async function remove(id: number) { if (!window.confirm('Bu rolü silmek istediğinize emin misiniz?')) return; try { await api.deleteRole(id); await roles.reload() } catch (cause) { window.alert(cause instanceof Error ? cause.message : 'Silme başarısız.') } }
  return <div><SectionHead title="Roller" description="Rollere bağlı izinleri controller bazlı düzenleyin." action={<Button onClick={() => setEditing('new')}><IconPlus className="h-4 w-4" /> Yeni Rol</Button>} />
    {roles.error ? <Panel className="p-6 text-rose-600">{roles.error}</Panel> : roles.loading ? <Panel className="p-6 text-muted-foreground">Yükleniyor…</Panel> : <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 xl:grid-cols-3">{(roles.data ?? []).map((role) => <Panel key={role.id} className="flex flex-col p-5"><div className="flex items-start justify-between"><div><h3 className="text-base font-bold text-navy-900">{role.name}</h3><p className="mt-0.5 text-sm text-muted-foreground">{role.description}</p></div><Badge tone={role.isActive ? 'active' : 'passive'}>{role.isActive ? 'Aktif' : 'Pasif'}</Badge></div><div className="mt-4 text-sm"><span className="block text-lg font-bold text-navy-900">{role.permissions.length}</span><span className="text-xs text-muted-foreground">İzin</span></div><div className="mt-4 flex gap-2 border-t border-navy-50 pt-4"><IconButton tone="edit" aria-label="Düzenle" onClick={() => setEditing(role)}><IconEdit className="h-4 w-4" /></IconButton>{!role.isSystemRole && <IconButton tone="delete" aria-label="Sil" onClick={() => remove(role.id)}><IconTrash className="h-4 w-4" /></IconButton>}</div></Panel>)}</div>}
    {editing && <RoleModal role={editing === 'new' ? null : editing} permissions={permissions.data ?? []} onClose={() => setEditing(null)} onSaved={roles.reload} />}
  </div>
}

function RoleModal({ role, permissions, onClose, onSaved }: { role: Role | null; permissions: Permission[]; onClose: () => void; onSaved: () => Promise<void> }) {
  const [draft, setDraft] = useState<RoleInput>(() => role ? { name: role.name, description: role.description ?? '', isActive: role.isActive, permissionIds: role.permissions.map((permission) => permission.id) } : { name: '', description: '', isActive: true, permissionIds: [] }); const [saving, setSaving] = useState(false)
  const groups = useMemo(() => {
    const grouped = new Map<string, Permission[]>()
    for (const permission of permissions) grouped.set(permission.controllerName, [...(grouped.get(permission.controllerName) ?? []), permission])
    return [...grouped.entries()]
  }, [permissions])
  function toggle(id: number, checked: boolean) { setDraft((current) => ({ ...current, permissionIds: checked ? [...current.permissionIds, id] : current.permissionIds.filter((item) => item !== id) })) }
  function toggleGroup(items: Permission[], checked: boolean) { setDraft((current) => ({ ...current, permissionIds: checked ? [...new Set([...current.permissionIds, ...items.map((item) => item.id)])] : current.permissionIds.filter((id) => !items.some((item) => item.id === id)) })) }
  async function save() { if (!draft.name.trim()) return window.alert('Rol adı zorunludur.'); setSaving(true); try { if (role) await api.updateRole(role.id, draft); else await api.createRole(draft); await onSaved(); onClose() } catch (cause) { window.alert(cause instanceof Error ? cause.message : 'Kayıt başarısız.') } finally { setSaving(false) } }
  return <Modal title={role ? 'Rol Düzenle' : 'Yeni Rol'} onClose={onClose} wide footer={<><Button variant="soft" onClick={onClose}>İptal</Button><Button disabled={saving} onClick={save}>{saving ? 'Kaydediliyor…' : 'Kaydet'}</Button></>}><div className="grid grid-cols-1 gap-4 sm:grid-cols-[1fr_auto] sm:items-end"><Field label="Rol Adı" hint="En fazla 100 karakter."><TextInput value={draft.name} onChange={(event) => setDraft((current) => ({ ...current, name: event.target.value }))} maxLength={100} required /></Field><div className="pb-2.5"><Check checked={draft.isActive} onChange={(isActive) => setDraft((current) => ({ ...current, isActive }))} label="Aktif" /></div></div><div className="mt-4"><Field label="Açıklama" hint="Rolün kullanım amacını belirtin."><Textarea value={draft.description} onChange={(event) => setDraft((current) => ({ ...current, description: event.target.value }))} maxLength={500} /></Field></div><div className="mt-5"><span className="mb-2 block text-sm font-medium text-navy-700">İzinler</span><p className="mb-3 text-xs text-muted-foreground">Bir controller başlığını işaretlemek, o controller altındaki tüm izinleri seçer.</p><div className="grid grid-cols-1 gap-3 sm:grid-cols-2">{groups.map(([controller, group]) => { const allSelected = group.length > 0 && group.every((item) => draft.permissionIds.includes(item.id)); return <div key={controller} className="overflow-hidden rounded-xl border border-navy-100"><div className="bg-navy-800 px-4 py-2.5"><Check checked={allSelected} onChange={(checked) => toggleGroup(group, checked)} label={<span className="font-semibold text-white">{controller}</span>} /></div><div className="flex flex-wrap gap-x-5 gap-y-2 px-4 py-3">{group.map((item) => <Check key={item.id} checked={draft.permissionIds.includes(item.id)} onChange={(checked) => toggle(item.id, checked)} label={item.name} />)}</div></div> })}</div></div></Modal>
}
