<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>BaseLib.Presentation</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Baselib.Entities/Baselib.Entities.csproj" />
    <Content Update="Data/*.json" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <Content Remove="node_modules/**" />
    <None Remove="node_modules/**" />
  </ItemGroup>
</Project>
